# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'airUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1254, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.toolBox_6 = QtWidgets.QToolBox(self.tab1)
        self.toolBox_6.setGeometry(QtCore.QRect(10, 20, 1091, 361))
        self.toolBox_6.setObjectName("toolBox_6")
        self.toolBox_6Page1 = QtWidgets.QWidget()
        self.toolBox_6Page1.setObjectName("toolBox_6Page1")
        self.groupBox_10 = QtWidgets.QGroupBox(self.toolBox_6Page1)
        self.groupBox_10.setGeometry(QtCore.QRect(490, -10, 211, 131))
        self.groupBox_10.setMaximumSize(QtCore.QSize(212, 131))
        self.groupBox_10.setAutoFillBackground(False)
        self.groupBox_10.setStyleSheet("")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_5.setObjectName("radioButton_5")
        self.statusButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.statusButtonGroup.setObjectName("statusButtonGroup")
        self.statusButtonGroup.addButton(self.radioButton_5)
        self.gridLayout_18.addWidget(self.radioButton_5, 2, 0, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_7.setObjectName("radioButton_7")
        self.statusButtonGroup.addButton(self.radioButton_7)
        self.gridLayout_18.addWidget(self.radioButton_7, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_10)
        self.label_9.setObjectName("label_9")
        self.gridLayout_18.addWidget(self.label_9, 0, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.statusButtonGroup.addButton(self.radioButton_6)
        self.gridLayout_18.addWidget(self.radioButton_6, 1, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.toolBox_6Page1)
        self.groupBox_11.setGeometry(QtCore.QRect(23, -10, 212, 131))
        self.groupBox_11.setMaximumSize(QtCore.QSize(212, 131))
        self.groupBox_11.setAutoFillBackground(False)
        self.groupBox_11.setStyleSheet("")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setFlat(False)
        self.groupBox_11.setCheckable(False)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_4.setObjectName("radioButton_4")
        self.classifButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.classifButtonGroup.setObjectName("classifButtonGroup")
        self.classifButtonGroup.addButton(self.radioButton_4)
        self.gridLayout_19.addWidget(self.radioButton_4, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_11)
        self.label_10.setObjectName("label_10")
        self.gridLayout_19.addWidget(self.label_10, 0, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_3.setObjectName("radioButton_3")
        self.classifButtonGroup.addButton(self.radioButton_3)
        self.gridLayout_19.addWidget(self.radioButton_3, 2, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.classifButtonGroup.addButton(self.radioButton_2)
        self.gridLayout_19.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.toolBox_6Page1)
        self.groupBox_8.setGeometry(QtCore.QRect(23, 110, 121, 91))
        self.groupBox_8.setMaximumSize(QtCore.QSize(212, 91))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        self.label_7.setObjectName("label_7")
        self.gridLayout_16.addWidget(self.label_7, 0, 0, 1, 1)
        self.dropEstado = QtWidgets.QComboBox(self.groupBox_8)
        self.dropEstado.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropEstado.setObjectName("dropEstado")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.dropEstado.addItem("")
        self.gridLayout_16.addWidget(self.dropEstado, 1, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.toolBox_6Page1)
        self.groupBox_9.setGeometry(QtCore.QRect(370, 110, 211, 91))
        self.groupBox_9.setMaximumSize(QtCore.QSize(211, 91))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_8 = QtWidgets.QLabel(self.groupBox_9)
        self.label_8.setObjectName("label_8")
        self.gridLayout_17.addWidget(self.label_8, 0, 0, 1, 1)
        self.dropTurno = QtWidgets.QComboBox(self.groupBox_9)
        self.dropTurno.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropTurno.setObjectName("dropTurno")
        self.dropTurno.addItem("")
        self.gridLayout_17.addWidget(self.dropTurno, 1, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.toolBox_6Page1)
        self.groupBox_17.setGeometry(QtCore.QRect(590, 110, 300, 91))
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_16 = QtWidgets.QLabel(self.groupBox_17)
        self.label_16.setObjectName("label_16")
        self.gridLayout_25.addWidget(self.label_16, 0, 0, 1, 1)
        self.dropTipoOco = QtWidgets.QComboBox(self.groupBox_17)
        self.dropTipoOco.setMinimumSize(QtCore.QSize(0, 0))
        self.dropTipoOco.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropTipoOco.setFrame(True)
        self.dropTipoOco.setObjectName("dropTipoOco")
        self.dropTipoOco.addItem("")
        self.gridLayout_25.addWidget(self.dropTipoOco, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.toolBox_6Page1)
        self.groupBox_5.setGeometry(QtCore.QRect(300, 190, 395, 91))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.dateTimeFrom = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.dateTimeFrom.setGeometry(QtCore.QRect(10, 50, 171, 25))
        self.dateTimeFrom.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeFrom.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeFrom.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dateTimeFrom.setCalendarPopup(True)
        self.dateTimeFrom.setObjectName("dateTimeFrom")
        self.dateTimeTo = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.dateTimeTo.setGeometry(QtCore.QRect(200, 50, 171, 25))
        self.dateTimeTo.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(23, 54, 59)))
        self.dateTimeTo.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeTo.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dateTimeTo.setCalendarPopup(True)
        self.dateTimeTo.setObjectName("dateTimeTo")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 173, 16))
        self.label_4.setObjectName("label_4")
        self.groupBox_12 = QtWidgets.QGroupBox(self.toolBox_6Page1)
        self.groupBox_12.setGeometry(QtCore.QRect(23, 190, 270, 91))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_11 = QtWidgets.QLabel(self.groupBox_12)
        self.label_11.setObjectName("label_11")
        self.gridLayout_20.addWidget(self.label_11, 0, 0, 1, 1)
        self.textCodigo = QtWidgets.QLineEdit(self.groupBox_12)
        self.textCodigo.setInputMask("")
        self.textCodigo.setText("")
        self.textCodigo.setObjectName("textCodigo")
        self.gridLayout_20.addWidget(self.textCodigo, 1, 0, 1, 1)
        self.groupBox_18 = QtWidgets.QGroupBox(self.toolBox_6Page1)
        self.groupBox_18.setGeometry(QtCore.QRect(150, 110, 212, 91))
        self.groupBox_18.setMaximumSize(QtCore.QSize(212, 91))
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_17 = QtWidgets.QLabel(self.groupBox_18)
        self.label_17.setObjectName("label_17")
        self.gridLayout_26.addWidget(self.label_17, 0, 0, 1, 1)
        self.dropCidade = QtWidgets.QComboBox(self.groupBox_18)
        self.dropCidade.setEnabled(False)
        self.dropCidade.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropCidade.setObjectName("dropCidade")
        self.dropCidade.addItem("")
        self.gridLayout_26.addWidget(self.dropCidade, 1, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.toolBox_6Page1)
        self.groupBox_19.setGeometry(QtCore.QRect(250, 10, 212, 91))
        self.groupBox_19.setMaximumSize(QtCore.QSize(212, 91))
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_19 = QtWidgets.QLabel(self.groupBox_19)
        self.label_19.setObjectName("label_19")
        self.gridLayout_28.addWidget(self.label_19, 0, 0, 1, 1)
        self.dropAerodromo = QtWidgets.QComboBox(self.groupBox_19)
        self.dropAerodromo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropAerodromo.setObjectName("dropAerodromo")
        self.dropAerodromo.addItem("")
        self.gridLayout_28.addWidget(self.dropAerodromo, 1, 0, 1, 1)
        self.toolBox_6.addItem(self.toolBox_6Page1, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.groupBox_13 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 0, 261, 91))
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.dropFabricante = QtWidgets.QComboBox(self.groupBox_13)
        self.dropFabricante.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropFabricante.setObjectName("dropFabricante")
        self.dropFabricante.addItem("")
        self.gridLayout_21.addWidget(self.dropFabricante, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_13)
        self.label_12.setObjectName("label_12")
        self.gridLayout_21.addWidget(self.label_12, 0, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_14.setGeometry(QtCore.QRect(450, 170, 211, 91))
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_13 = QtWidgets.QLabel(self.groupBox_14)
        self.label_13.setObjectName("label_13")
        self.gridLayout_22.addWidget(self.label_13, 0, 0, 1, 1)
        self.dropCategoriaPeso = QtWidgets.QComboBox(self.groupBox_14)
        self.dropCategoriaPeso.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropCategoriaPeso.setObjectName("dropCategoriaPeso")
        self.dropCategoriaPeso.addItem("")
        self.gridLayout_22.addWidget(self.dropCategoriaPeso, 1, 0, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_15.setGeometry(QtCore.QRect(590, 50, 211, 91))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_14 = QtWidgets.QLabel(self.groupBox_15)
        self.label_14.setObjectName("label_14")
        self.gridLayout_23.addWidget(self.label_14, 0, 0, 1, 1)
        self.dropQtdMotores = QtWidgets.QComboBox(self.groupBox_15)
        self.dropQtdMotores.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropQtdMotores.setObjectName("dropQtdMotores")
        self.dropQtdMotores.addItem("")
        self.gridLayout_23.addWidget(self.dropQtdMotores, 1, 0, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 100, 212, 91))
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.dropTipoAeronave = QtWidgets.QComboBox(self.groupBox_16)
        self.dropTipoAeronave.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropTipoAeronave.setObjectName("dropTipoAeronave")
        self.dropTipoAeronave.addItem("")
        self.gridLayout_24.addWidget(self.dropTipoAeronave, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_16)
        self.label_15.setObjectName("label_15")
        self.gridLayout_24.addWidget(self.label_15, 0, 0, 1, 1)
        self.groupBox_33 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_33.setGeometry(QtCore.QRect(280, 0, 261, 91))
        self.groupBox_33.setTitle("")
        self.groupBox_33.setObjectName("groupBox_33")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.groupBox_33)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.dropModelo = QtWidgets.QComboBox(self.groupBox_33)
        self.dropModelo.setEnabled(False)
        self.dropModelo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropModelo.setObjectName("dropModelo")
        self.dropModelo.addItem("")
        self.gridLayout_42.addWidget(self.dropModelo, 1, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_33)
        self.label_33.setObjectName("label_33")
        self.gridLayout_42.addWidget(self.label_33, 0, 0, 1, 1)
        self.groupBox_34 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_34.setGeometry(QtCore.QRect(10, 180, 261, 91))
        self.groupBox_34.setTitle("")
        self.groupBox_34.setObjectName("groupBox_34")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.groupBox_34)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.dropFabricante_4 = QtWidgets.QComboBox(self.groupBox_34)
        self.dropFabricante_4.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropFabricante_4.setObjectName("dropFabricante_4")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.dropFabricante_4.addItem("")
        self.gridLayout_43.addWidget(self.dropFabricante_4, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_34)
        self.label_34.setObjectName("label_34")
        self.gridLayout_43.addWidget(self.label_34, 0, 0, 1, 1)
        self.groupBox_35 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_35.setGeometry(QtCore.QRect(280, 100, 212, 91))
        self.groupBox_35.setTitle("")
        self.groupBox_35.setObjectName("groupBox_35")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.groupBox_35)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.dropDano = QtWidgets.QComboBox(self.groupBox_35)
        self.dropDano.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropDano.setObjectName("dropDano")
        self.dropDano.addItem("")
        self.gridLayout_44.addWidget(self.dropDano, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_35)
        self.label_35.setObjectName("label_35")
        self.gridLayout_44.addWidget(self.label_35, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_7.setGeometry(QtCore.QRect(690, 140, 211, 131))
        self.groupBox_7.setMaximumSize(QtCore.QSize(212, 131))
        self.groupBox_7.setAutoFillBackground(False)
        self.groupBox_7.setStyleSheet("")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setCheckable(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout_15.addWidget(self.radioButton_11, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 0, 0, 1, 1)
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_12.setChecked(True)
        self.radioButton_12.setObjectName("radioButton_12")
        self.gridLayout_15.addWidget(self.radioButton_12, 1, 0, 1, 1)
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_13.setObjectName("radioButton_13")
        self.gridLayout_15.addWidget(self.radioButton_13, 3, 0, 1, 1)
        self.toolBox_6.addItem(self.page_5, "")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab1)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 460, 1171, 298))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tableResultadosOco = QtWidgets.QTableWidget(self.tab_10)
        self.tableResultadosOco.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableResultadosOco.setAlternatingRowColors(True)
        self.tableResultadosOco.setObjectName("tableResultadosOco")
        self.tableResultadosOco.setColumnCount(10)
        self.tableResultadosOco.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(112, 112, 112))
        self.tableResultadosOco.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosOco.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosOco.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosOco.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosOco.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosOco.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosOco.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosOco.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosOco.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosOco.setHorizontalHeaderItem(9, item)
        self.tableResultadosOco.verticalHeader().setVisible(False)
        self.gridLayout_13.addWidget(self.tableResultadosOco, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableResultadosAero = QtWidgets.QTableWidget(self.tab)
        self.tableResultadosAero.setGeometry(QtCore.QRect(11, 11, 1145, 243))
        self.tableResultadosAero.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableResultadosAero.setAlternatingRowColors(True)
        self.tableResultadosAero.setObjectName("tableResultadosAero")
        self.tableResultadosAero.setColumnCount(8)
        self.tableResultadosAero.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(112, 112, 112))
        self.tableResultadosAero.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosAero.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosAero.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosAero.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosAero.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosAero.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosAero.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultadosAero.setHorizontalHeaderItem(7, item)
        self.tableResultadosAero.verticalHeader().setVisible(False)
        self.tabWidget_3.addTab(self.tab, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_9)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 14, 1141, 241))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.buscarButton = QtWidgets.QPushButton(self.tab1)
        self.buscarButton.setGeometry(QtCore.QRect(930, 390, 121, 41))
        self.buscarButton.setObjectName("buscarButton")
        self.limparButton = QtWidgets.QPushButton(self.tab1)
        self.limparButton.setGeometry(QtCore.QRect(790, 390, 121, 41))
        self.limparButton.setStyleSheet("selection-background-color: rgb(170, 0, 0);")
        self.limparButton.setObjectName("limparButton")
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, -10, 1168, 741))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.toolBox_7 = QtWidgets.QToolBox(self.groupBox)
        self.toolBox_7.setGeometry(QtCore.QRect(20, 40, 1131, 691))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolBox_7.setFont(font)
        self.toolBox_7.setObjectName("toolBox_7")
        self.toolBox_6Page1_2 = QtWidgets.QWidget()
        self.toolBox_6Page1_2.setGeometry(QtCore.QRect(0, 0, 1131, 625))
        self.toolBox_6Page1_2.setObjectName("toolBox_6Page1_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.toolBox_6Page1_2)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(9, -10, 1101, 271))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_26.setGeometry(QtCore.QRect(180, 170, 241, 91))
        self.groupBox_26.setTitle("")
        self.groupBox_26.setObjectName("groupBox_26")
        self.label_26 = QtWidgets.QLabel(self.groupBox_26)
        self.label_26.setGeometry(QtCore.QRect(38, 34, 121, 16))
        self.label_26.setObjectName("label_26")
        self.toc13NumRelatOco = QtWidgets.QLineEdit(self.groupBox_26)
        self.toc13NumRelatOco.setGeometry(QtCore.QRect(14, 60, 213, 24))
        self.toc13NumRelatOco.setInputMask("")
        self.toc13NumRelatOco.setText("")
        self.toc13NumRelatOco.setObjectName("toc13NumRelatOco")
        self.coc14RelatPublOco = QtWidgets.QCheckBox(self.groupBox_26)
        self.coc14RelatPublOco.setGeometry(QtCore.QRect(14, 34, 17, 18))
        self.coc14RelatPublOco.setText("")
        self.coc14RelatPublOco.setObjectName("coc14RelatPublOco")
        self.groupBox_46 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_46.setGeometry(QtCore.QRect(10, 170, 161, 91))
        self.groupBox_46.setTitle("")
        self.groupBox_46.setObjectName("groupBox_46")
        self.coc18SaidaPistaOco = QtWidgets.QCheckBox(self.groupBox_46)
        self.coc18SaidaPistaOco.setGeometry(QtCore.QRect(14, 34, 17, 18))
        self.coc18SaidaPistaOco.setText("")
        self.coc18SaidaPistaOco.setObjectName("coc18SaidaPistaOco")
        self.label_46 = QtWidgets.QLabel(self.groupBox_46)
        self.label_46.setGeometry(QtCore.QRect(38, 34, 87, 16))
        self.label_46.setObjectName("label_46")
        self.label_27 = QtWidgets.QLabel(self.groupBox_46)
        self.label_27.setGeometry(QtCore.QRect(38, 60, 109, 16))
        self.label_27.setObjectName("label_27")
        self.coc12StatusInvestOco = QtWidgets.QCheckBox(self.groupBox_46)
        self.coc12StatusInvestOco.setGeometry(QtCore.QRect(14, 60, 17, 18))
        self.coc12StatusInvestOco.setText("")
        self.coc12StatusInvestOco.setObjectName("coc12StatusInvestOco")
        self.groupBox_41 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_41.setGeometry(QtCore.QRect(750, 90, 161, 91))
        self.groupBox_41.setTitle("")
        self.groupBox_41.setObjectName("groupBox_41")
        self.label_41 = QtWidgets.QLabel(self.groupBox_41)
        self.label_41.setGeometry(QtCore.QRect(14, 34, 55, 16))
        self.label_41.setObjectName("label_41")
        self.toc4LongitudeOco = QtWidgets.QLineEdit(self.groupBox_41)
        self.toc4LongitudeOco.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.toc4LongitudeOco.setInputMask("")
        self.toc4LongitudeOco.setText("")
        self.toc4LongitudeOco.setObjectName("toc4LongitudeOco")
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_25.setGeometry(QtCore.QRect(10, 10, 161, 91))
        self.groupBox_25.setTitle("")
        self.groupBox_25.setObjectName("groupBox_25")
        self.label_25 = QtWidgets.QLabel(self.groupBox_25)
        self.label_25.setGeometry(QtCore.QRect(14, 34, 123, 16))
        self.label_25.setObjectName("label_25")
        self.toc0CodOco = QtWidgets.QLineEdit(self.groupBox_25)
        self.toc0CodOco.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.toc0CodOco.setInputMask("")
        self.toc0CodOco.setText("")
        self.toc0CodOco.setObjectName("toc0CodOco")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(700, 10, 211, 91))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.dtoc910DataHoraOco = QtWidgets.QDateTimeEdit(self.groupBox_6)
        self.dtoc910DataHoraOco.setGeometry(QtCore.QRect(10, 55, 191, 24))
        self.dtoc910DataHoraOco.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dtoc910DataHoraOco.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dtoc910DataHoraOco.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dtoc910DataHoraOco.setCalendarPopup(True)
        self.dtoc910DataHoraOco.setObjectName("dtoc910DataHoraOco")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(14, 34, 173, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox_44 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_44.setGeometry(QtCore.QRect(180, 90, 241, 91))
        self.groupBox_44.setTitle("")
        self.groupBox_44.setObjectName("groupBox_44")
        self.label_44 = QtWidgets.QLabel(self.groupBox_44)
        self.label_44.setGeometry(QtCore.QRect(14, 34, 39, 16))
        self.label_44.setObjectName("label_44")
        self.toc5CidadeOco = QtWidgets.QLineEdit(self.groupBox_44)
        self.toc5CidadeOco.setGeometry(QtCore.QRect(14, 57, 213, 24))
        self.toc5CidadeOco.setInputMask("")
        self.toc5CidadeOco.setText("")
        self.toc5CidadeOco.setObjectName("toc5CidadeOco")
        self.groupBox_47 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_47.setGeometry(QtCore.QRect(920, 90, 171, 91))
        self.groupBox_47.setTitle("")
        self.groupBox_47.setObjectName("groupBox_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_47)
        self.label_48.setGeometry(QtCore.QRect(14, 34, 141, 16))
        self.label_48.setObjectName("label_48")
        self.soc17NumAeronavesEnv = QtWidgets.QSpinBox(self.groupBox_47)
        self.soc17NumAeronavesEnv.setGeometry(QtCore.QRect(14, 57, 143, 24))
        self.soc17NumAeronavesEnv.setMinimum(1)
        self.soc17NumAeronavesEnv.setMaximum(300)
        self.soc17NumAeronavesEnv.setObjectName("soc17NumAeronavesEnv")
        self.groupBox_40 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_40.setGeometry(QtCore.QRect(580, 90, 161, 91))
        self.groupBox_40.setTitle("")
        self.groupBox_40.setObjectName("groupBox_40")
        self.label_40 = QtWidgets.QLabel(self.groupBox_40)
        self.label_40.setGeometry(QtCore.QRect(14, 34, 45, 16))
        self.label_40.setObjectName("label_40")
        self.toc3LatitudeOco = QtWidgets.QLineEdit(self.groupBox_40)
        self.toc3LatitudeOco.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.toc3LatitudeOco.setInputMask("")
        self.toc3LatitudeOco.setText("")
        self.toc3LatitudeOco.setObjectName("toc3LatitudeOco")
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_22.setGeometry(QtCore.QRect(10, 90, 161, 91))
        self.groupBox_22.setMaximumSize(QtCore.QSize(212, 91))
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.groupBox_22)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.doc6EstadoOco = QtWidgets.QComboBox(self.groupBox_22)
        self.doc6EstadoOco.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.doc6EstadoOco.setObjectName("doc6EstadoOco")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.doc6EstadoOco.addItem("")
        self.gridLayout_31.addWidget(self.doc6EstadoOco, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_22)
        self.label_22.setObjectName("label_22")
        self.gridLayout_31.addWidget(self.label_22, 0, 0, 1, 1)
        self.groupBox_45 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_45.setGeometry(QtCore.QRect(430, 90, 141, 91))
        self.groupBox_45.setTitle("")
        self.groupBox_45.setObjectName("groupBox_45")
        self.label_45 = QtWidgets.QLabel(self.groupBox_45)
        self.label_45.setGeometry(QtCore.QRect(14, 34, 106, 16))
        self.label_45.setObjectName("label_45")
        self.toc8AerodromeOco = QtWidgets.QLineEdit(self.groupBox_45)
        self.toc8AerodromeOco.setGeometry(QtCore.QRect(14, 57, 113, 24))
        self.toc8AerodromeOco.setInputMask("")
        self.toc8AerodromeOco.setText("")
        self.toc8AerodromeOco.setObjectName("toc8AerodromeOco")
        self.groupBox_39 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_39.setGeometry(QtCore.QRect(180, 10, 341, 91))
        self.groupBox_39.setTitle("")
        self.groupBox_39.setObjectName("groupBox_39")
        self.label_39 = QtWidgets.QLabel(self.groupBox_39)
        self.label_39.setGeometry(QtCore.QRect(14, 34, 109, 16))
        self.label_39.setObjectName("label_39")
        self.toc2TipoOco = QtWidgets.QLineEdit(self.groupBox_39)
        self.toc2TipoOco.setGeometry(QtCore.QRect(14, 57, 313, 24))
        self.toc2TipoOco.setInputMask("")
        self.toc2TipoOco.setText("")
        self.toc2TipoOco.setObjectName("toc2TipoOco")
        self.limparRegOco = QtWidgets.QPushButton(self.groupBox_2)
        self.limparRegOco.setGeometry(QtCore.QRect(840, 190, 71, 71))
        self.limparRegOco.setStyleSheet("selection-background-color: rgb(170, 0, 0);")
        self.limparRegOco.setObjectName("limparRegOco")
        self.registrarRegOco = QtWidgets.QPushButton(self.groupBox_2)
        self.registrarRegOco.setGeometry(QtCore.QRect(920, 190, 171, 71))
        self.registrarRegOco.setObjectName("registrarRegOco")
        self.groupBoxPublicacao = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBoxPublicacao.setGeometry(QtCore.QRect(430, 170, 221, 91))
        self.groupBoxPublicacao.setTitle("")
        self.groupBoxPublicacao.setObjectName("groupBoxPublicacao")
        self.dtoc15DataPublicRelat = QtWidgets.QDateTimeEdit(self.groupBoxPublicacao)
        self.dtoc15DataPublicRelat.setGeometry(QtCore.QRect(14, 60, 201, 24))
        self.dtoc15DataPublicRelat.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dtoc15DataPublicRelat.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dtoc15DataPublicRelat.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dtoc15DataPublicRelat.setCalendarPopup(True)
        self.dtoc15DataPublicRelat.setObjectName("dtoc15DataPublicRelat")
        self.coc15TemDataRelat = QtWidgets.QCheckBox(self.groupBoxPublicacao)
        self.coc15TemDataRelat.setGeometry(QtCore.QRect(14, 34, 17, 18))
        self.coc15TemDataRelat.setText("")
        self.coc15TemDataRelat.setObjectName("coc15TemDataRelat")
        self.label_51 = QtWidgets.QLabel(self.groupBoxPublicacao)
        self.label_51.setGeometry(QtCore.QRect(38, 34, 121, 16))
        self.label_51.setObjectName("label_51")
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_27.setGeometry(QtCore.QRect(920, 10, 171, 91))
        self.groupBox_27.setTitle("")
        self.groupBox_27.setObjectName("groupBox_27")
        self.label_42 = QtWidgets.QLabel(self.groupBox_27)
        self.label_42.setGeometry(QtCore.QRect(14, 34, 126, 16))
        self.label_42.setObjectName("label_42")
        self.toc16Recomend = QtWidgets.QLineEdit(self.groupBox_27)
        self.toc16Recomend.setGeometry(QtCore.QRect(14, 57, 143, 24))
        self.toc16Recomend.setInputMask("")
        self.toc16Recomend.setText("")
        self.toc16Recomend.setObjectName("toc16Recomend")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_23.setGeometry(QtCore.QRect(530, 10, 161, 91))
        self.groupBox_23.setMaximumSize(QtCore.QSize(212, 91))
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.doc1Classif = QtWidgets.QComboBox(self.groupBox_23)
        self.doc1Classif.setGeometry(QtCore.QRect(14, 57, 133, 20))
        self.doc1Classif.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.doc1Classif.setObjectName("doc1Classif")
        self.doc1Classif.addItem("")
        self.doc1Classif.addItem("")
        self.doc1Classif.addItem("")
        self.label_23 = QtWidgets.QLabel(self.groupBox_23)
        self.label_23.setGeometry(QtCore.QRect(14, 34, 73, 16))
        self.label_23.setObjectName("label_23")
        self.groupBox_3 = QtWidgets.QGroupBox(self.toolBox_6Page1_2)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 270, 1101, 351))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_50 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_50.setGeometry(QtCore.QRect(10, 90, 161, 91))
        self.groupBox_50.setTitle("")
        self.groupBox_50.setObjectName("groupBox_50")
        self.label_52 = QtWidgets.QLabel(self.groupBox_50)
        self.label_52.setGeometry(QtCore.QRect(14, 34, 60, 16))
        self.label_52.setObjectName("label_52")
        self.tae4Fabricante = QtWidgets.QLineEdit(self.groupBox_50)
        self.tae4Fabricante.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae4Fabricante.setInputMask("")
        self.tae4Fabricante.setText("")
        self.tae4Fabricante.setObjectName("tae4Fabricante")
        self.groupBox_51 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_51.setGeometry(QtCore.QRect(180, 170, 161, 91))
        self.groupBox_51.setTitle("")
        self.groupBox_51.setObjectName("groupBox_51")
        self.label_53 = QtWidgets.QLabel(self.groupBox_51)
        self.label_53.setGeometry(QtCore.QRect(14, 34, 133, 16))
        self.label_53.setObjectName("label_53")
        self.tae8QtdMotores = QtWidgets.QLineEdit(self.groupBox_51)
        self.tae8QtdMotores.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae8QtdMotores.setInputMask("")
        self.tae8QtdMotores.setText("")
        self.tae8QtdMotores.setObjectName("tae8QtdMotores")
        self.groupBox_52 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_52.setGeometry(QtCore.QRect(10, 10, 161, 91))
        self.groupBox_52.setTitle("")
        self.groupBox_52.setObjectName("groupBox_52")
        self.label_54 = QtWidgets.QLabel(self.groupBox_52)
        self.label_54.setGeometry(QtCore.QRect(14, 34, 123, 16))
        self.label_54.setObjectName("label_54")
        self.tae0CodOco = QtWidgets.QLineEdit(self.groupBox_52)
        self.tae0CodOco.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae0CodOco.setInputMask("")
        self.tae0CodOco.setText("")
        self.tae0CodOco.setObjectName("tae0CodOco")
        self.groupBox_54 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_54.setGeometry(QtCore.QRect(350, 90, 161, 91))
        self.groupBox_54.setTitle("")
        self.groupBox_54.setObjectName("groupBox_54")
        self.label_55 = QtWidgets.QLabel(self.groupBox_54)
        self.label_55.setGeometry(QtCore.QRect(14, 34, 72, 16))
        self.label_55.setObjectName("label_55")
        self.tae6TipoICAO = QtWidgets.QLineEdit(self.groupBox_54)
        self.tae6TipoICAO.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae6TipoICAO.setInputMask("")
        self.tae6TipoICAO.setText("")
        self.tae6TipoICAO.setObjectName("tae6TipoICAO")
        self.groupBox_56 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_56.setGeometry(QtCore.QRect(180, 90, 161, 91))
        self.groupBox_56.setTitle("")
        self.groupBox_56.setObjectName("groupBox_56")
        self.label_57 = QtWidgets.QLabel(self.groupBox_56)
        self.label_57.setGeometry(QtCore.QRect(14, 34, 41, 16))
        self.label_57.setObjectName("label_57")
        self.tae5Modelo = QtWidgets.QLineEdit(self.groupBox_56)
        self.tae5Modelo.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae5Modelo.setInputMask("")
        self.tae5Modelo.setText("")
        self.tae5Modelo.setObjectName("tae5Modelo")
        self.groupBox_57 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_57.setGeometry(QtCore.QRect(10, 170, 161, 91))
        self.groupBox_57.setTitle("")
        self.groupBox_57.setObjectName("groupBox_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_57)
        self.label_58.setGeometry(QtCore.QRect(14, 34, 80, 16))
        self.label_58.setObjectName("label_58")
        self.tae7TipoMotor = QtWidgets.QLineEdit(self.groupBox_57)
        self.tae7TipoMotor.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae7TipoMotor.setInputMask("")
        self.tae7TipoMotor.setText("")
        self.tae7TipoMotor.setObjectName("tae7TipoMotor")
        self.groupBox_58 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_58.setGeometry(QtCore.QRect(690, 170, 141, 91))
        self.groupBox_58.setMaximumSize(QtCore.QSize(212, 91))
        self.groupBox_58.setTitle("")
        self.groupBox_58.setObjectName("groupBox_58")
        self.dae10CategPesoMax = QtWidgets.QComboBox(self.groupBox_58)
        self.dae10CategPesoMax.setGeometry(QtCore.QRect(14, 57, 113, 20))
        self.dae10CategPesoMax.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dae10CategPesoMax.setObjectName("dae10CategPesoMax")
        self.dae10CategPesoMax.addItem("")
        self.dae10CategPesoMax.addItem("")
        self.dae10CategPesoMax.addItem("")
        self.dae10CategPesoMax.addItem("")
        self.label_24 = QtWidgets.QLabel(self.groupBox_58)
        self.label_24.setGeometry(QtCore.QRect(14, 34, 86, 16))
        self.label_24.setObjectName("label_24")
        self.groupBox_59 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_59.setGeometry(QtCore.QRect(520, 10, 161, 91))
        self.groupBox_59.setTitle("")
        self.groupBox_59.setObjectName("groupBox_59")
        self.label_59 = QtWidgets.QLabel(self.groupBox_59)
        self.label_59.setGeometry(QtCore.QRect(14, 34, 92, 16))
        self.label_59.setObjectName("label_59")
        self.tae14PaisRegistro = QtWidgets.QLineEdit(self.groupBox_59)
        self.tae14PaisRegistro.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae14PaisRegistro.setInputMask("")
        self.tae14PaisRegistro.setText("")
        self.tae14PaisRegistro.setObjectName("tae14PaisRegistro")
        self.groupBox_61 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_61.setGeometry(QtCore.QRect(350, 10, 161, 91))
        self.groupBox_61.setTitle("")
        self.groupBox_61.setObjectName("groupBox_61")
        self.label_61 = QtWidgets.QLabel(self.groupBox_61)
        self.label_61.setGeometry(QtCore.QRect(14, 34, 101, 16))
        self.label_61.setObjectName("label_61")
        self.tae3TipoAero = QtWidgets.QLineEdit(self.groupBox_61)
        self.tae3TipoAero.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae3TipoAero.setInputMask("")
        self.tae3TipoAero.setText("")
        self.tae3TipoAero.setObjectName("tae3TipoAero")
        self.groupBox_62 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_62.setGeometry(QtCore.QRect(180, 10, 161, 91))
        self.groupBox_62.setTitle("")
        self.groupBox_62.setObjectName("groupBox_62")
        self.label_62 = QtWidgets.QLabel(self.groupBox_62)
        self.label_62.setGeometry(QtCore.QRect(14, 34, 128, 16))
        self.label_62.setObjectName("label_62")
        self.tae1Matricula = QtWidgets.QLineEdit(self.groupBox_62)
        self.tae1Matricula.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae1Matricula.setInputMask("")
        self.tae1Matricula.setText("")
        self.tae1Matricula.setObjectName("tae1Matricula")
        self.groupBox_63 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_63.setGeometry(QtCore.QRect(840, 10, 251, 91))
        self.groupBox_63.setTitle("")
        self.groupBox_63.setObjectName("groupBox_63")
        self.label_63 = QtWidgets.QLabel(self.groupBox_63)
        self.label_63.setGeometry(QtCore.QRect(14, 34, 131, 16))
        self.label_63.setObjectName("label_63")
        self.tae2CategOperador = QtWidgets.QLineEdit(self.groupBox_63)
        self.tae2CategOperador.setGeometry(QtCore.QRect(14, 57, 223, 24))
        self.tae2CategOperador.setInputMask("")
        self.tae2CategOperador.setText("")
        self.tae2CategOperador.setObjectName("tae2CategOperador")
        self.groupBox_64 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_64.setGeometry(QtCore.QRect(520, 170, 161, 91))
        self.groupBox_64.setTitle("")
        self.groupBox_64.setObjectName("groupBox_64")
        self.label_64 = QtWidgets.QLabel(self.groupBox_64)
        self.label_64.setGeometry(QtCore.QRect(14, 34, 121, 16))
        self.label_64.setObjectName("label_64")
        self.tae9PesoMax = QtWidgets.QLineEdit(self.groupBox_64)
        self.tae9PesoMax.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae9PesoMax.setInputMask("")
        self.tae9PesoMax.setText("")
        self.tae9PesoMax.setObjectName("tae9PesoMax")
        self.groupBox_65 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_65.setGeometry(QtCore.QRect(350, 170, 161, 91))
        self.groupBox_65.setTitle("")
        self.groupBox_65.setObjectName("groupBox_65")
        self.label_65 = QtWidgets.QLabel(self.groupBox_65)
        self.label_65.setGeometry(QtCore.QRect(14, 34, 118, 16))
        self.label_65.setObjectName("label_65")
        self.tae11NumAssentos = QtWidgets.QLineEdit(self.groupBox_65)
        self.tae11NumAssentos.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae11NumAssentos.setInputMask("")
        self.tae11NumAssentos.setText("")
        self.tae11NumAssentos.setObjectName("tae11NumAssentos")
        self.groupBox_66 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_66.setGeometry(QtCore.QRect(690, 90, 141, 91))
        self.groupBox_66.setTitle("")
        self.groupBox_66.setObjectName("groupBox_66")
        self.label_66 = QtWidgets.QLabel(self.groupBox_66)
        self.label_66.setGeometry(QtCore.QRect(14, 34, 106, 16))
        self.label_66.setObjectName("label_66")
        self.dt12AnoFabric = QtWidgets.QDateEdit(self.groupBox_66)
        self.dt12AnoFabric.setGeometry(QtCore.QRect(14, 57, 113, 24))
        self.dt12AnoFabric.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.dt12AnoFabric.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.dt12AnoFabric.setObjectName("dt12AnoFabric")
        self.groupBox_53 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_53.setGeometry(QtCore.QRect(520, 90, 161, 91))
        self.groupBox_53.setTitle("")
        self.groupBox_53.setObjectName("groupBox_53")
        self.label_67 = QtWidgets.QLabel(self.groupBox_53)
        self.label_67.setGeometry(QtCore.QRect(14, 34, 105, 16))
        self.label_67.setObjectName("label_67")
        self.tae13PaisFabric = QtWidgets.QLineEdit(self.groupBox_53)
        self.tae13PaisFabric.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae13PaisFabric.setInputMask("")
        self.tae13PaisFabric.setText("")
        self.tae13PaisFabric.setObjectName("tae13PaisFabric")
        self.groupBox_67 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_67.setGeometry(QtCore.QRect(690, 10, 141, 91))
        self.groupBox_67.setTitle("")
        self.groupBox_67.setObjectName("groupBox_67")
        self.label_68 = QtWidgets.QLabel(self.groupBox_67)
        self.label_68.setGeometry(QtCore.QRect(14, 34, 65, 16))
        self.label_68.setObjectName("label_68")
        self.tae22Fatalidades = QtWidgets.QLineEdit(self.groupBox_67)
        self.tae22Fatalidades.setGeometry(QtCore.QRect(14, 57, 113, 24))
        self.tae22Fatalidades.setInputMask("")
        self.tae22Fatalidades.setText("")
        self.tae22Fatalidades.setObjectName("tae22Fatalidades")
        self.groupBox_60 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_60.setGeometry(QtCore.QRect(690, 250, 141, 91))
        self.groupBox_60.setMaximumSize(QtCore.QSize(212, 91))
        self.groupBox_60.setTitle("")
        self.groupBox_60.setObjectName("groupBox_60")
        self.dae21DanoAeronave = QtWidgets.QComboBox(self.groupBox_60)
        self.dae21DanoAeronave.setGeometry(QtCore.QRect(14, 57, 113, 20))
        self.dae21DanoAeronave.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dae21DanoAeronave.setObjectName("dae21DanoAeronave")
        self.dae21DanoAeronave.addItem("")
        self.dae21DanoAeronave.addItem("")
        self.dae21DanoAeronave.addItem("")
        self.dae21DanoAeronave.addItem("")
        self.dae21DanoAeronave.addItem("")
        self.label_49 = QtWidgets.QLabel(self.groupBox_60)
        self.label_49.setGeometry(QtCore.QRect(14, 34, 98, 16))
        self.label_49.setObjectName("label_49")
        self.groupBox_68 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_68.setGeometry(QtCore.QRect(10, 250, 161, 91))
        self.groupBox_68.setTitle("")
        self.groupBox_68.setObjectName("groupBox_68")
        self.label_60 = QtWidgets.QLabel(self.groupBox_68)
        self.label_60.setGeometry(QtCore.QRect(14, 34, 106, 16))
        self.label_60.setObjectName("label_60")
        self.tae15RegCategoria = QtWidgets.QLineEdit(self.groupBox_68)
        self.tae15RegCategoria.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae15RegCategoria.setInputMask("")
        self.tae15RegCategoria.setText("")
        self.tae15RegCategoria.setObjectName("tae15RegCategoria")
        self.groupBox_69 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_69.setGeometry(QtCore.QRect(180, 250, 161, 91))
        self.groupBox_69.setTitle("")
        self.groupBox_69.setObjectName("groupBox_69")
        self.label_69 = QtWidgets.QLabel(self.groupBox_69)
        self.label_69.setGeometry(QtCore.QRect(14, 34, 109, 16))
        self.label_69.setObjectName("label_69")
        self.tae16RegSegmento = QtWidgets.QLineEdit(self.groupBox_69)
        self.tae16RegSegmento.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae16RegSegmento.setInputMask("")
        self.tae16RegSegmento.setText("")
        self.tae16RegSegmento.setObjectName("tae16RegSegmento")
        self.groupBox_70 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_70.setGeometry(QtCore.QRect(520, 250, 161, 91))
        self.groupBox_70.setTitle("")
        self.groupBox_70.setObjectName("groupBox_70")
        self.label_70 = QtWidgets.QLabel(self.groupBox_70)
        self.label_70.setGeometry(QtCore.QRect(14, 34, 86, 16))
        self.label_70.setObjectName("label_70")
        self.tae18VooDestino = QtWidgets.QLineEdit(self.groupBox_70)
        self.tae18VooDestino.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae18VooDestino.setInputMask("")
        self.tae18VooDestino.setText("")
        self.tae18VooDestino.setObjectName("tae18VooDestino")
        self.groupBox_71 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_71.setGeometry(QtCore.QRect(350, 250, 161, 91))
        self.groupBox_71.setTitle("")
        self.groupBox_71.setObjectName("groupBox_71")
        self.label_71 = QtWidgets.QLabel(self.groupBox_71)
        self.label_71.setGeometry(QtCore.QRect(14, 34, 86, 16))
        self.label_71.setObjectName("label_71")
        self.tae17VooOrigem = QtWidgets.QLineEdit(self.groupBox_71)
        self.tae17VooOrigem.setGeometry(QtCore.QRect(14, 57, 133, 24))
        self.tae17VooOrigem.setInputMask("")
        self.tae17VooOrigem.setText("")
        self.tae17VooOrigem.setObjectName("tae17VooOrigem")
        self.groupBox_72 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_72.setGeometry(QtCore.QRect(840, 170, 251, 91))
        self.groupBox_72.setTitle("")
        self.groupBox_72.setObjectName("groupBox_72")
        self.label_72 = QtWidgets.QLabel(self.groupBox_72)
        self.label_72.setGeometry(QtCore.QRect(14, 34, 104, 16))
        self.label_72.setObjectName("label_72")
        self.tae19FaseOperacao = QtWidgets.QLineEdit(self.groupBox_72)
        self.tae19FaseOperacao.setGeometry(QtCore.QRect(14, 57, 223, 24))
        self.tae19FaseOperacao.setInputMask("")
        self.tae19FaseOperacao.setText("")
        self.tae19FaseOperacao.setObjectName("tae19FaseOperacao")
        self.groupBox_73 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_73.setGeometry(QtCore.QRect(840, 90, 251, 91))
        self.groupBox_73.setTitle("")
        self.groupBox_73.setObjectName("groupBox_73")
        self.label_73 = QtWidgets.QLabel(self.groupBox_73)
        self.label_73.setGeometry(QtCore.QRect(14, 34, 102, 16))
        self.label_73.setObjectName("label_73")
        self.tae20TipoOperacao = QtWidgets.QLineEdit(self.groupBox_73)
        self.tae20TipoOperacao.setGeometry(QtCore.QRect(14, 57, 223, 24))
        self.tae20TipoOperacao.setInputMask("")
        self.tae20TipoOperacao.setText("")
        self.tae20TipoOperacao.setObjectName("tae20TipoOperacao")
        self.registrarRegAero = QtWidgets.QPushButton(self.groupBox_3)
        self.registrarRegAero.setGeometry(QtCore.QRect(920, 270, 171, 71))
        self.registrarRegAero.setObjectName("registrarRegAero")
        self.limparRegAero = QtWidgets.QPushButton(self.groupBox_3)
        self.limparRegAero.setGeometry(QtCore.QRect(840, 270, 71, 71))
        self.limparRegAero.setStyleSheet("selection-background-color: rgb(170, 0, 0);")
        self.limparRegAero.setObjectName("limparRegAero")
        self.toolBox_7.addItem(self.toolBox_6Page1_2, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 1131, 629))
        self.page_6.setObjectName("page_6")
        self.groupBox_28 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_28.setGeometry(QtCore.QRect(10, 0, 261, 91))
        self.groupBox_28.setTitle("")
        self.groupBox_28.setObjectName("groupBox_28")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.groupBox_28)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.dropFabricante_2 = QtWidgets.QComboBox(self.groupBox_28)
        self.dropFabricante_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropFabricante_2.setObjectName("dropFabricante_2")
        self.dropFabricante_2.addItem("")
        self.gridLayout_37.addWidget(self.dropFabricante_2, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_28)
        self.label_28.setObjectName("label_28")
        self.gridLayout_37.addWidget(self.label_28, 0, 0, 1, 1)
        self.groupBox_29 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_29.setGeometry(QtCore.QRect(450, 170, 211, 91))
        self.groupBox_29.setTitle("")
        self.groupBox_29.setObjectName("groupBox_29")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.groupBox_29)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.label_29 = QtWidgets.QLabel(self.groupBox_29)
        self.label_29.setObjectName("label_29")
        self.gridLayout_38.addWidget(self.label_29, 0, 0, 1, 1)
        self.dropCategoriaPeso_2 = QtWidgets.QComboBox(self.groupBox_29)
        self.dropCategoriaPeso_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropCategoriaPeso_2.setObjectName("dropCategoriaPeso_2")
        self.dropCategoriaPeso_2.addItem("")
        self.gridLayout_38.addWidget(self.dropCategoriaPeso_2, 1, 0, 1, 1)
        self.groupBox_30 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_30.setGeometry(QtCore.QRect(590, 50, 211, 91))
        self.groupBox_30.setTitle("")
        self.groupBox_30.setObjectName("groupBox_30")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.groupBox_30)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.label_30 = QtWidgets.QLabel(self.groupBox_30)
        self.label_30.setObjectName("label_30")
        self.gridLayout_39.addWidget(self.label_30, 0, 0, 1, 1)
        self.dropQtdMotores_2 = QtWidgets.QComboBox(self.groupBox_30)
        self.dropQtdMotores_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropQtdMotores_2.setObjectName("dropQtdMotores_2")
        self.dropQtdMotores_2.addItem("")
        self.gridLayout_39.addWidget(self.dropQtdMotores_2, 1, 0, 1, 1)
        self.groupBox_31 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_31.setGeometry(QtCore.QRect(10, 100, 212, 91))
        self.groupBox_31.setTitle("")
        self.groupBox_31.setObjectName("groupBox_31")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.groupBox_31)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.dropTipoAeronave_2 = QtWidgets.QComboBox(self.groupBox_31)
        self.dropTipoAeronave_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropTipoAeronave_2.setObjectName("dropTipoAeronave_2")
        self.dropTipoAeronave_2.addItem("")
        self.gridLayout_40.addWidget(self.dropTipoAeronave_2, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_31)
        self.label_31.setObjectName("label_31")
        self.gridLayout_40.addWidget(self.label_31, 0, 0, 1, 1)
        self.groupBox_36 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_36.setGeometry(QtCore.QRect(280, 0, 261, 91))
        self.groupBox_36.setTitle("")
        self.groupBox_36.setObjectName("groupBox_36")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.groupBox_36)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.dropModelo_2 = QtWidgets.QComboBox(self.groupBox_36)
        self.dropModelo_2.setEnabled(False)
        self.dropModelo_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropModelo_2.setObjectName("dropModelo_2")
        self.dropModelo_2.addItem("")
        self.gridLayout_45.addWidget(self.dropModelo_2, 1, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_36)
        self.label_36.setObjectName("label_36")
        self.gridLayout_45.addWidget(self.label_36, 0, 0, 1, 1)
        self.groupBox_37 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_37.setGeometry(QtCore.QRect(10, 180, 261, 91))
        self.groupBox_37.setTitle("")
        self.groupBox_37.setObjectName("groupBox_37")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.groupBox_37)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.dropFabricante_5 = QtWidgets.QComboBox(self.groupBox_37)
        self.dropFabricante_5.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropFabricante_5.setObjectName("dropFabricante_5")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.dropFabricante_5.addItem("")
        self.gridLayout_46.addWidget(self.dropFabricante_5, 1, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_37)
        self.label_37.setObjectName("label_37")
        self.gridLayout_46.addWidget(self.label_37, 0, 0, 1, 1)
        self.groupBox_38 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_38.setGeometry(QtCore.QRect(280, 100, 212, 91))
        self.groupBox_38.setTitle("")
        self.groupBox_38.setObjectName("groupBox_38")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.groupBox_38)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.dropDano_2 = QtWidgets.QComboBox(self.groupBox_38)
        self.dropDano_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dropDano_2.setObjectName("dropDano_2")
        self.dropDano_2.addItem("")
        self.gridLayout_47.addWidget(self.dropDano_2, 1, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_38)
        self.label_38.setObjectName("label_38")
        self.gridLayout_47.addWidget(self.label_38, 0, 0, 1, 1)
        self.groupBox_32 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_32.setGeometry(QtCore.QRect(690, 140, 211, 131))
        self.groupBox_32.setMaximumSize(QtCore.QSize(212, 131))
        self.groupBox_32.setAutoFillBackground(False)
        self.groupBox_32.setStyleSheet("")
        self.groupBox_32.setTitle("")
        self.groupBox_32.setFlat(False)
        self.groupBox_32.setCheckable(False)
        self.groupBox_32.setObjectName("groupBox_32")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.groupBox_32)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_32)
        self.radioButton_17.setObjectName("radioButton_17")
        self.gridLayout_41.addWidget(self.radioButton_17, 2, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_32)
        self.label_32.setObjectName("label_32")
        self.gridLayout_41.addWidget(self.label_32, 0, 0, 1, 1)
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox_32)
        self.radioButton_18.setChecked(True)
        self.radioButton_18.setObjectName("radioButton_18")
        self.gridLayout_41.addWidget(self.radioButton_18, 1, 0, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(self.groupBox_32)
        self.radioButton_19.setObjectName("radioButton_19")
        self.gridLayout_41.addWidget(self.radioButton_19, 3, 0, 1, 1)
        self.toolBox_7.addItem(self.page_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1254, 25))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuSobre = QtWidgets.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.menuMenu.addAction(self.actionSalvar)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionSair)
        self.menuSobre.addAction(self.actionSobre)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #MainWindow.setTabOrder(MainWindow.horizontalSlider, MainWindow.textEdit)
        #MainWindow.setTabOrder(MainWindow.textEdit, MainWindow.verticalSlider)
        #MainWindow.setTabOrder(MainWindow.verticalSlider, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_5.setText(_translate("MainWindow", "Em Andamento"))
        self.radioButton_7.setText(_translate("MainWindow", "Finalizado"))
        self.label_9.setText(_translate("MainWindow", "Status Investigativo"))
        self.radioButton_6.setText(_translate("MainWindow", "Qualquer"))
        self.radioButton_4.setText(_translate("MainWindow", "Incidente"))
        self.label_10.setText(_translate("MainWindow", "Classificação"))
        self.radioButton_3.setText(_translate("MainWindow", "Acidente"))
        self.radioButton_2.setText(_translate("MainWindow", "Qualquer"))
        self.label_7.setText(_translate("MainWindow", "Estado/UF"))
        self.dropEstado.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.dropEstado.setItemText(1, _translate("MainWindow", "Acre (AC)"))
        self.dropEstado.setItemText(2, _translate("MainWindow", "Alagoas (AL)"))
        self.dropEstado.setItemText(3, _translate("MainWindow", "Amapá (AP)"))
        self.dropEstado.setItemText(4, _translate("MainWindow", "Amazonas (AM)"))
        self.dropEstado.setItemText(5, _translate("MainWindow", "Bahia (BA)"))
        self.dropEstado.setItemText(6, _translate("MainWindow", "Ceará (CE)"))
        self.dropEstado.setItemText(7, _translate("MainWindow", "Distrito Federal (DF)"))
        self.dropEstado.setItemText(8, _translate("MainWindow", "Espírito Santo (Amém)"))
        self.dropEstado.setItemText(9, _translate("MainWindow", "Goiás (GO)"))
        self.dropEstado.setItemText(10, _translate("MainWindow", "Maranhão (MA)"))
        self.dropEstado.setItemText(11, _translate("MainWindow", "Mato Grosso (MT)"))
        self.dropEstado.setItemText(12, _translate("MainWindow", "Mato Grosso do Sul (MS)"))
        self.dropEstado.setItemText(13, _translate("MainWindow", "Minas Gerais (MG)"))
        self.dropEstado.setItemText(14, _translate("MainWindow", "Pará (PA)"))
        self.dropEstado.setItemText(15, _translate("MainWindow", "Paraíba (PB)"))
        self.dropEstado.setItemText(16, _translate("MainWindow", "Paraná (PR)"))
        self.dropEstado.setItemText(17, _translate("MainWindow", "Pernambuco (PE)"))
        self.dropEstado.setItemText(18, _translate("MainWindow", "Piauí (PI)"))
        self.dropEstado.setItemText(19, _translate("MainWindow", "Rio de Janeiro (RJ)"))
        self.dropEstado.setItemText(20, _translate("MainWindow", "Rio Grande do Norte (RN)"))
        self.dropEstado.setItemText(21, _translate("MainWindow", "Rio Grande do Sul (RS)"))
        self.dropEstado.setItemText(22, _translate("MainWindow", "Rondônia (RO)"))
        self.dropEstado.setItemText(23, _translate("MainWindow", "Roraima (RR)"))
        self.dropEstado.setItemText(24, _translate("MainWindow", "Santa Catarina (SC)"))
        self.dropEstado.setItemText(25, _translate("MainWindow", "São Paulo (SP)"))
        self.dropEstado.setItemText(26, _translate("MainWindow", "Sergipe (SE)"))
        self.dropEstado.setItemText(27, _translate("MainWindow", "Tocantins (TO)"))
        self.label_8.setText(_translate("MainWindow", "Turno do Dia"))
        self.dropTurno.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_16.setText(_translate("MainWindow", "Tipo"))
        self.dropTipoOco.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_4.setText(_translate("MainWindow", "Período de Tempo"))
        self.label_11.setText(_translate("MainWindow", "Código Identificador (Completo ou Parcial)"))
        self.textCodigo.setPlaceholderText(_translate("MainWindow", " ID (numérico)"))
        self.label_17.setText(_translate("MainWindow", "Cidade"))
        self.dropCidade.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_19.setText(_translate("MainWindow", "Aeródromo"))
        self.dropAerodromo.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.toolBox_6.setItemText(self.toolBox_6.indexOf(self.toolBox_6Page1), _translate("MainWindow", "Ocorrências"))
        self.dropFabricante.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_12.setText(_translate("MainWindow", "Fabricante"))
        self.label_13.setText(_translate("MainWindow", "Categoria de Peso"))
        self.dropCategoriaPeso.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_14.setText(_translate("MainWindow", "Quantidade de Motores"))
        self.dropQtdMotores.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.dropTipoAeronave.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_15.setText(_translate("MainWindow", "Tipo"))
        self.dropModelo.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_33.setText(_translate("MainWindow", "Modelo"))
        self.dropFabricante_4.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.dropFabricante_4.setItemText(1, _translate("MainWindow", "Acre (AC)"))
        self.dropFabricante_4.setItemText(2, _translate("MainWindow", "Alagoas (AL)"))
        self.dropFabricante_4.setItemText(3, _translate("MainWindow", "Amapá (AP)"))
        self.dropFabricante_4.setItemText(4, _translate("MainWindow", "Amazonas (AM)"))
        self.dropFabricante_4.setItemText(5, _translate("MainWindow", "Bahia (BA)"))
        self.dropFabricante_4.setItemText(6, _translate("MainWindow", "Ceará (CE)"))
        self.dropFabricante_4.setItemText(7, _translate("MainWindow", "Distrito Federal (DF)"))
        self.dropFabricante_4.setItemText(8, _translate("MainWindow", "Espírito Santo (Amém)"))
        self.dropFabricante_4.setItemText(9, _translate("MainWindow", "Goiás (GO)"))
        self.dropFabricante_4.setItemText(10, _translate("MainWindow", "Maranhão (MA)"))
        self.dropFabricante_4.setItemText(11, _translate("MainWindow", "Mato Grosso (MT)"))
        self.dropFabricante_4.setItemText(12, _translate("MainWindow", "Mato Grosso do Sul (MS)"))
        self.dropFabricante_4.setItemText(13, _translate("MainWindow", "Minas Gerais (MG)"))
        self.dropFabricante_4.setItemText(14, _translate("MainWindow", "Pará (PA)"))
        self.dropFabricante_4.setItemText(15, _translate("MainWindow", "Paraíba (PB)"))
        self.dropFabricante_4.setItemText(16, _translate("MainWindow", "Paraná (PR)"))
        self.dropFabricante_4.setItemText(17, _translate("MainWindow", "Pernambuco (PE)"))
        self.dropFabricante_4.setItemText(18, _translate("MainWindow", "Piauí (PI)"))
        self.dropFabricante_4.setItemText(19, _translate("MainWindow", "Rio de Janeiro (RJ)"))
        self.dropFabricante_4.setItemText(20, _translate("MainWindow", "Rio Grande do Norte (RN)"))
        self.dropFabricante_4.setItemText(21, _translate("MainWindow", "Rio Grande do Sul (RS)"))
        self.dropFabricante_4.setItemText(22, _translate("MainWindow", "Rondônia (RO)"))
        self.dropFabricante_4.setItemText(23, _translate("MainWindow", "Roraima (RR)"))
        self.dropFabricante_4.setItemText(24, _translate("MainWindow", "Santa Catarina (SC)"))
        self.dropFabricante_4.setItemText(25, _translate("MainWindow", "São Paulo (SP)"))
        self.dropFabricante_4.setItemText(26, _translate("MainWindow", "Sergipe (SE)"))
        self.dropFabricante_4.setItemText(27, _translate("MainWindow", "Tocantins (TO)"))
        self.label_34.setText(_translate("MainWindow", "Fabricante"))
        self.dropDano.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_35.setText(_translate("MainWindow", "Dano"))
        self.radioButton_11.setText(_translate("MainWindow", "Fatal"))
        self.label_6.setText(_translate("MainWindow", "Fatalidade"))
        self.radioButton_12.setText(_translate("MainWindow", "Qualquer"))
        self.radioButton_13.setText(_translate("MainWindow", "Não Fatal"))
        self.toolBox_6.setItemText(self.toolBox_6.indexOf(self.page_5), _translate("MainWindow", "Aeronaves Envolvidas"))
        self.tableResultadosOco.setSortingEnabled(True)
        item = self.tableResultadosOco.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableResultadosOco.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Classificação"))
        item = self.tableResultadosOco.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tipo de Ocorrência"))
        item = self.tableResultadosOco.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cidade"))
        item = self.tableResultadosOco.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "UF"))
        item = self.tableResultadosOco.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Aeródromo"))
        item = self.tableResultadosOco.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Dia e Hora"))
        item = self.tableResultadosOco.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Turno do Dia"))
        item = self.tableResultadosOco.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Investigação"))
        item = self.tableResultadosOco.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "# Aeronaves"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Resultados Ocorrências"))
        self.tableResultadosAero.setSortingEnabled(True)
        item = self.tableResultadosAero.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableResultadosAero.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tipo de Aeronave"))
        item = self.tableResultadosAero.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fabricante"))
        item = self.tableResultadosAero.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Modelo"))
        item = self.tableResultadosAero.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "# Motores"))
        item = self.tableResultadosAero.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Classe"))
        item = self.tableResultadosAero.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Dano"))
        item = self.tableResultadosAero.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Fatalidades"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("MainWindow", "Resultados Aeronaves"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Ranking"))
        self.buscarButton.setText(_translate("MainWindow", "Buscar"))
        self.limparButton.setText(_translate("MainWindow", "Limpar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Busca"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Ocorrência"))
        self.label_26.setText(_translate("MainWindow", "Relatório Publicado?"))
        self.toc13NumRelatOco.setPlaceholderText(_translate("MainWindow", "Código (alfanumérico)"))
        self.label_46.setText(_translate("MainWindow", "Saída da Pista?"))
        self.label_27.setText(_translate("MainWindow", "Investigação Ativa?"))
        self.label_41.setText(_translate("MainWindow", "Longitude"))
        self.toc4LongitudeOco.setPlaceholderText(_translate("MainWindow", "Coord (numérico)"))
        self.label_25.setText(_translate("MainWindow", "Código da Ocorrência"))
        self.toc0CodOco.setPlaceholderText(_translate("MainWindow", " ID (numérico)"))
        self.label_5.setText(_translate("MainWindow", "Data e Hora da Ocorrência"))
        self.label_44.setText(_translate("MainWindow", "Cidade"))
        self.toc5CidadeOco.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_48.setText(_translate("MainWindow", "Nº Aeronaves Envolvidas"))
        self.label_40.setText(_translate("MainWindow", "Latitude"))
        self.toc3LatitudeOco.setPlaceholderText(_translate("MainWindow", "Coord (numérico)"))
        self.doc6EstadoOco.setItemText(0, _translate("MainWindow", "***"))
        self.doc6EstadoOco.setItemText(1, _translate("MainWindow", "AC"))
        self.doc6EstadoOco.setItemText(2, _translate("MainWindow", "AL"))
        self.doc6EstadoOco.setItemText(3, _translate("MainWindow", "AP"))
        self.doc6EstadoOco.setItemText(4, _translate("MainWindow", "AM"))
        self.doc6EstadoOco.setItemText(5, _translate("MainWindow", "BA"))
        self.doc6EstadoOco.setItemText(6, _translate("MainWindow", "CE"))
        self.doc6EstadoOco.setItemText(7, _translate("MainWindow", "DF"))
        self.doc6EstadoOco.setItemText(8, _translate("MainWindow", "ES"))
        self.doc6EstadoOco.setItemText(9, _translate("MainWindow", "GO"))
        self.doc6EstadoOco.setItemText(10, _translate("MainWindow", "MA"))
        self.doc6EstadoOco.setItemText(11, _translate("MainWindow", "MT"))
        self.doc6EstadoOco.setItemText(12, _translate("MainWindow", "MS"))
        self.doc6EstadoOco.setItemText(13, _translate("MainWindow", "MG"))
        self.doc6EstadoOco.setItemText(14, _translate("MainWindow", "PA"))
        self.doc6EstadoOco.setItemText(15, _translate("MainWindow", "PB"))
        self.doc6EstadoOco.setItemText(16, _translate("MainWindow", "PR"))
        self.doc6EstadoOco.setItemText(17, _translate("MainWindow", "PE"))
        self.doc6EstadoOco.setItemText(18, _translate("MainWindow", "PI"))
        self.doc6EstadoOco.setItemText(19, _translate("MainWindow", "RJ"))
        self.doc6EstadoOco.setItemText(20, _translate("MainWindow", "RN"))
        self.doc6EstadoOco.setItemText(21, _translate("MainWindow", "RS"))
        self.doc6EstadoOco.setItemText(22, _translate("MainWindow", "RO"))
        self.doc6EstadoOco.setItemText(23, _translate("MainWindow", "RR"))
        self.doc6EstadoOco.setItemText(24, _translate("MainWindow", "SC"))
        self.doc6EstadoOco.setItemText(25, _translate("MainWindow", "SP"))
        self.doc6EstadoOco.setItemText(26, _translate("MainWindow", "SE"))
        self.doc6EstadoOco.setItemText(27, _translate("MainWindow", "TO"))
        self.label_22.setText(_translate("MainWindow", "Estado/UF"))
        self.label_45.setText(_translate("MainWindow", "Aeródromo (Sigla)"))
        self.toc8AerodromeOco.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_39.setText(_translate("MainWindow", "Tipo de Ocorrência"))
        self.toc2TipoOco.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.limparRegOco.setText(_translate("MainWindow", "Limpar"))
        self.registrarRegOco.setText(_translate("MainWindow", "Registrar"))
        self.label_51.setText(_translate("MainWindow", "Data de Publicação?"))
        self.label_42.setText(_translate("MainWindow", "Total Recomendações"))
        self.toc16Recomend.setPlaceholderText(_translate("MainWindow", " Qtd (numérico)"))
        self.doc1Classif.setItemText(0, _translate("MainWindow", "Acidente"))
        self.doc1Classif.setItemText(1, _translate("MainWindow", "Incidente"))
        self.doc1Classif.setItemText(2, _translate("MainWindow", "Incidente Grave"))
        self.label_23.setText(_translate("MainWindow", "Classificação"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Aeronave"))
        self.label_52.setText(_translate("MainWindow", "Fabricante"))
        self.tae4Fabricante.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_53.setText(_translate("MainWindow", "Quantidade de Motores"))
        self.tae8QtdMotores.setPlaceholderText(_translate("MainWindow", "Ex: Monomotor, Bimotor..."))
        self.label_54.setText(_translate("MainWindow", "Código da Ocorrência"))
        self.tae0CodOco.setPlaceholderText(_translate("MainWindow", " ID (numérico)"))
        self.label_55.setText(_translate("MainWindow", "Código ICAO"))
        self.tae6TipoICAO.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_57.setText(_translate("MainWindow", "Modelo"))
        self.tae5Modelo.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_58.setText(_translate("MainWindow", "Tipo de Motor"))
        self.tae7TipoMotor.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.dae10CategPesoMax.setItemText(0, _translate("MainWindow", "***"))
        self.dae10CategPesoMax.setItemText(1, _translate("MainWindow", "Leve"))
        self.dae10CategPesoMax.setItemText(2, _translate("MainWindow", "Média"))
        self.dae10CategPesoMax.setItemText(3, _translate("MainWindow", "Pesada"))
        self.label_24.setText(_translate("MainWindow", "Categoria Peso"))
        self.label_59.setText(_translate("MainWindow", "País de Registro"))
        self.tae14PaisRegistro.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_61.setText(_translate("MainWindow", "Tipo de Aeronave"))
        self.tae3TipoAero.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_62.setText(_translate("MainWindow", "Matrícula da Aeronave"))
        self.tae1Matricula.setPlaceholderText(_translate("MainWindow", "ID (alfanumérico)"))
        self.label_63.setText(_translate("MainWindow", "Categoria do Operador"))
        self.tae2CategOperador.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_64.setText(_translate("MainWindow", "Peso Máx Decolagem"))
        self.tae9PesoMax.setPlaceholderText(_translate("MainWindow", "Kgs (numérico)"))
        self.label_65.setText(_translate("MainWindow", "Número de Assentos"))
        self.tae11NumAssentos.setPlaceholderText(_translate("MainWindow", "Qtd (numérico)"))
        self.label_66.setText(_translate("MainWindow", "Ano de Fabricação"))
        self.dt12AnoFabric.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.label_67.setText(_translate("MainWindow", "País do Fabricante"))
        self.tae13PaisFabric.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_68.setText(_translate("MainWindow", "Fatalidades"))
        self.tae22Fatalidades.setPlaceholderText(_translate("MainWindow", "Qtd (numérico)"))
        self.dae21DanoAeronave.setItemText(0, _translate("MainWindow", "***"))
        self.dae21DanoAeronave.setItemText(1, _translate("MainWindow", "Nenhum"))
        self.dae21DanoAeronave.setItemText(2, _translate("MainWindow", "Leve"))
        self.dae21DanoAeronave.setItemText(3, _translate("MainWindow", "Substancial"))
        self.dae21DanoAeronave.setItemText(4, _translate("MainWindow", "Destruída"))
        self.label_49.setText(_translate("MainWindow", "Dano à Aeronave"))
        self.label_60.setText(_translate("MainWindow", "Registro Categoria"))
        self.tae15RegCategoria.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_69.setText(_translate("MainWindow", "Registro Segmento"))
        self.tae16RegSegmento.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_70.setText(_translate("MainWindow", "Destino do Vôo"))
        self.tae18VooDestino.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_71.setText(_translate("MainWindow", "Origem do Vôo"))
        self.tae17VooOrigem.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_72.setText(_translate("MainWindow", "Fase de Operação"))
        self.tae19FaseOperacao.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.label_73.setText(_translate("MainWindow", "Tipo de Operação"))
        self.tae20TipoOperacao.setPlaceholderText(_translate("MainWindow", "Digite aqui..."))
        self.registrarRegAero.setText(_translate("MainWindow", "Registrar"))
        self.limparRegAero.setText(_translate("MainWindow", "Limpar"))
        self.toolBox_7.setItemText(self.toolBox_7.indexOf(self.toolBox_6Page1_2), _translate("MainWindow", "Adicionar ou Alterar Dados"))
        self.dropFabricante_2.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_28.setText(_translate("MainWindow", "Fabricante"))
        self.label_29.setText(_translate("MainWindow", "Categoria de Peso"))
        self.dropCategoriaPeso_2.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_30.setText(_translate("MainWindow", "Quantidade de Motores"))
        self.dropQtdMotores_2.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.dropTipoAeronave_2.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_31.setText(_translate("MainWindow", "Tipo"))
        self.dropModelo_2.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_36.setText(_translate("MainWindow", "Modelo"))
        self.dropFabricante_5.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.dropFabricante_5.setItemText(1, _translate("MainWindow", "Acre (AC)"))
        self.dropFabricante_5.setItemText(2, _translate("MainWindow", "Alagoas (AL)"))
        self.dropFabricante_5.setItemText(3, _translate("MainWindow", "Amapá (AP)"))
        self.dropFabricante_5.setItemText(4, _translate("MainWindow", "Amazonas (AM)"))
        self.dropFabricante_5.setItemText(5, _translate("MainWindow", "Bahia (BA)"))
        self.dropFabricante_5.setItemText(6, _translate("MainWindow", "Ceará (CE)"))
        self.dropFabricante_5.setItemText(7, _translate("MainWindow", "Distrito Federal (DF)"))
        self.dropFabricante_5.setItemText(8, _translate("MainWindow", "Espírito Santo (Amém)"))
        self.dropFabricante_5.setItemText(9, _translate("MainWindow", "Goiás (GO)"))
        self.dropFabricante_5.setItemText(10, _translate("MainWindow", "Maranhão (MA)"))
        self.dropFabricante_5.setItemText(11, _translate("MainWindow", "Mato Grosso (MT)"))
        self.dropFabricante_5.setItemText(12, _translate("MainWindow", "Mato Grosso do Sul (MS)"))
        self.dropFabricante_5.setItemText(13, _translate("MainWindow", "Minas Gerais (MG)"))
        self.dropFabricante_5.setItemText(14, _translate("MainWindow", "Pará (PA)"))
        self.dropFabricante_5.setItemText(15, _translate("MainWindow", "Paraíba (PB)"))
        self.dropFabricante_5.setItemText(16, _translate("MainWindow", "Paraná (PR)"))
        self.dropFabricante_5.setItemText(17, _translate("MainWindow", "Pernambuco (PE)"))
        self.dropFabricante_5.setItemText(18, _translate("MainWindow", "Piauí (PI)"))
        self.dropFabricante_5.setItemText(19, _translate("MainWindow", "Rio de Janeiro (RJ)"))
        self.dropFabricante_5.setItemText(20, _translate("MainWindow", "Rio Grande do Norte (RN)"))
        self.dropFabricante_5.setItemText(21, _translate("MainWindow", "Rio Grande do Sul (RS)"))
        self.dropFabricante_5.setItemText(22, _translate("MainWindow", "Rondônia (RO)"))
        self.dropFabricante_5.setItemText(23, _translate("MainWindow", "Roraima (RR)"))
        self.dropFabricante_5.setItemText(24, _translate("MainWindow", "Santa Catarina (SC)"))
        self.dropFabricante_5.setItemText(25, _translate("MainWindow", "São Paulo (SP)"))
        self.dropFabricante_5.setItemText(26, _translate("MainWindow", "Sergipe (SE)"))
        self.dropFabricante_5.setItemText(27, _translate("MainWindow", "Tocantins (TO)"))
        self.label_37.setText(_translate("MainWindow", "Fabricante"))
        self.dropDano_2.setItemText(0, _translate("MainWindow", "Qualquer"))
        self.label_38.setText(_translate("MainWindow", "Dano"))
        self.radioButton_17.setText(_translate("MainWindow", "Fatal"))
        self.label_32.setText(_translate("MainWindow", "Fatalidade"))
        self.radioButton_18.setText(_translate("MainWindow", "Qualquer"))
        self.radioButton_19.setText(_translate("MainWindow", "Não Fatal"))
        self.toolBox_7.setItemText(self.toolBox_7.indexOf(self.page_6), _translate("MainWindow", "Aeronaves Envolvidas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Inserir/Remover"))
        self.menuMenu.setTitle(_translate("MainWindow", "&Menu"))
        self.menuSobre.setTitle(_translate("MainWindow", "Sobre"))
        self.actionSalvar.setText(_translate("MainWindow", "&Salvar Resultados"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSair.setToolTip(_translate("MainWindow", "Fechar o airsort"))
        self.actionSair.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre airsort"))

